import json

stub_gitlab_api_v4_user_json = json.loads(
    (
        "{"
        '"id": 18503717,'
        '"username": "project_51648656_bot_cf8fee5361c1f81143b20c1d38860e94",'
        '"name": "GitHub",'
        '"state": "active",'
        '"locked": false,'
        '"avatar_url": "https://secure.gravatar.com/avatar/0f6b9438a785de51cc940904f0294b91?s=80&d=identicon",'
        '"web_url": "https://gitlab.com/project_51648656_bot_cf8fee5361c1f81143b20c1d38860e94",'
        '"created_at": "2023-10-27T16:21:38.693Z",'
        '"bio": "",'
        '"location": "",'
        '"public_email": null,'
        '"skype": "",'
        '"linkedin": "",'
        '"twitter": "",'
        '"discord": "",'
        '"website_url": "",'
        '"organization": "",'
        '"job_title": "",'
        '"pronouns": null,'
        '"bot": true,'
        '"work_information": null,'
        '"local_time": null,'
        '"last_sign_in_at": null,'
        '"confirmed_at": "2023-10-27T16:21:38.667Z",'
        '"last_activity_on": "2023-10-27",'
        '"email": "project_51648656_bot_cf8fee5361c1f81143b20c1d38860e94@noreply.gitlab.com",'
        '"theme_id": 3,'
        '"color_scheme_id": 1,'
        '"projects_limit": 100000,'
        '"current_sign_in_at": null,'
        '"identities": [],'
        '"can_create_group": true,'
        '"can_create_project": true,'
        '"two_factor_enabled": false,'
        '"external": false,'
        '"private_profile": false,'
        '"commit_email": "project_51648656_bot_cf8fee5361c1f81143b20c1d38860e94@noreply.gitlab.com",'
        '"shared_runners_minutes_limit": null,'
        '"extra_shared_runners_minutes_limit": null,'
        '"scim_identities": []'
        "}"
    )
)


stub_gitlab_api_v4_401_unauthorized_json = json.loads('{"message": "401 Unauthorized"}')


stub_gitlab_api_v4_projects_json = json.loads(
    (
        "[{"
        '  "id": 51708305,'
        '  "description": "description_for_test_search",'
        '  "name": "ex02.20 - Medidas de um círculo",'
        '  "name_with_namespace": "Deitel Cpp Como Programar - 5ª edição / Capítulo 02 / Exercícios / ex02.20 - Medidas de um círculo",'
        '  "path": "ex02.20-medidas-de-um-circulo",'
        '  "path_with_namespace": "deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios/ex02.20-medidas-de-um-circulo",'
        '  "created_at": "2023-10-30T10:54:23.427Z",'
        '  "default_branch": "main",'
        '  "tag_list": [],'
        '  "topics": [],'
        '  "ssh_url_to_repo": "git@gitlab.com:deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios/ex02.20-medidas-de-um-circulo.git",'
        '  "http_url_to_repo": "https://gitlab.com/deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios/ex02.20-medidas-de-um-circulo.git",'
        '  "web_url": "https://gitlab.com/deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios/ex02.20-medidas-de-um-circulo",'
        '  "readme_url": "https://gitlab.com/deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios/ex02.20-medidas-de-um-circulo/-/blob/main/README.md",'
        '  "forks_count": 0,'
        '  "avatar_url": null,'
        '  "star_count": 0,'
        '  "last_activity_at": "2023-10-30T10:54:23.427Z",'
        '  "namespace": {'
        '      "id": 76920210,'
        '      "name": "Exercícios",'
        '      "path": "exercicios",'
        '      "kind": "group",'
        '      "full_path": "deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios",'
        '      "parent_id": 76634432,'
        '      "avatar_url": null,'
        '      "web_url": "https://gitlab.com/groups/deitel-cpp-como-programar-5-edicao/capitulo-02/exercicios"'
        "}"
        "},"
        "{"
        '  "id": 51708266,'
        '  "description": null,'
        '  "name": "News Bulletin",'
        '  "name_with_namespace": "vanshika baghel / News Bulletin",'
        '  "path": "news-bulletin",'
        '  "path_with_namespace": "baghel2/news-bulletin",'
        '  "created_at": "2023-10-30T10:53:01.657Z",'
        '  "default_branch": "main",'
        '  "tag_list": [],'
        '  "topics": [],'
        '  "ssh_url_to_repo": "git@gitlab.com:baghel2/news-bulletin.git",'
        '  "http_url_to_repo": "https://gitlab.com/baghel2/news-bulletin.git",'
        '  "web_url": "https://gitlab.com/baghel2/news-bulletin",'
        '  "readme_url": "https://gitlab.com/baghel2/news-bulletin/-/blob/main/README.md",'
        '  "forks_count": 0,'
        '  "avatar_url": null,'
        '  "star_count": 0,'
        '  "last_activity_at": "2023-10-30T10:53:01.657Z",'
        '  "namespace": {'
        '      "id": 66272390,'
        '      "name": "vanshika baghel",'
        '      "path": "baghel2",'
        '      "kind": "user",'
        '      "full_path": "baghel2",'
        '      "parent_id": null,'
        '      "avatar_url": "/uploads/-/system/user/avatar/14274097/avatar.png",'
        '      "web_url": "https://gitlab.com/baghel2"'
        "  }"
        "}]"
    )
)


stub_gitlab_api_v4_project_51648656_json = json.loads(
    (
        "{"
        '    "id": 51648656,'
        '    "description": null,'
        '    "name": "GitLabAPI",'
        '    "name_with_namespace": "undeadgrishnackh / GitLabAPI",'
        '    "path": "GitLabAPI",'
        '    "path_with_namespace": "undeadgrishnackh1/GitLabAPI",'
        '    "created_at": "2023-10-27T16:04:57.003Z",'
        '    "default_branch": "main",'
        '    "tag_list": [],'
        '    "topics": [],'
        '    "ssh_url_to_repo": "git@gitlab.com:undeadgrishnackh1/GitLabAPI.git",'
        '    "http_url_to_repo": "https://gitlab.com/undeadgrishnackh1/GitLabAPI.git",'
        '    "web_url": "https://gitlab.com/undeadgrishnackh1/GitLabAPI",'
        '    "readme_url": "https://gitlab.com/undeadgrishnackh1/GitLabAPI/-/blob/main/README.md",'
        '    "forks_count": 0,'
        '    "avatar_url": null,'
        '    "star_count": 0,'
        '    "last_activity_at": "2023-10-27T16:04:57.003Z",'
        '    "namespace": {'
        '        "id": 77049747,'
        '        "name": "undeadgrishnackh",'
        '        "path": "undeadgrishnackh1",'
        '        "kind": "group",'
        '        "full_path": "undeadgrishnackh1",'
        '        "parent_id": null,'
        '        "avatar_url": null,'
        '       "web_url": "https://gitlab.com/groups/undeadgrishnackh1"'
        "    },"
        '    "container_registry_image_prefix": "registry.gitlab.com/undeadgrishnackh1/gitlabapi",'
        '    "_links": {'
        '        "self": "https://gitlab.com/api/v4/projects/51648656",'
        '        "issues": "https://gitlab.com/api/v4/projects/51648656/issues",'
        '        "merge_requests": "https://gitlab.com/api/v4/projects/51648656/merge_requests",'
        '        "repo_branches": "https://gitlab.com/api/v4/projects/51648656/repository/branches",'
        '        "labels": "https://gitlab.com/api/v4/projects/51648656/labels",'
        '        "events": "https://gitlab.com/api/v4/projects/51648656/events",'
        '        "members": "https://gitlab.com/api/v4/projects/51648656/members",'
        '       "cluster_agents": "https://gitlab.com/api/v4/projects/51648656/cluster_agents"'
        "    },"
        '    "packages_enabled": true,'
        '    "empty_repo": false,'
        '    "archived": false,'
        '    "visibility": "private",'
        '    "resolve_outdated_diff_discussions": false,'
        '    "container_expiration_policy": {'
        '        "cadence": "1d",'
        '        "enabled": false,'
        '        "keep_n": 10,'
        '        "older_than": "90d",'
        '        "name_regex": ".*",'
        '        "name_regex_keep": null,'
        '       "next_run_at": "2023-10-28T16:04:57.039Z"'
        "    },"
        '    "issues_enabled": true,'
        '    "merge_requests_enabled": true,'
        '    "wiki_enabled": true,'
        '    "jobs_enabled": true,'
        '    "snippets_enabled": true,'
        '    "container_registry_enabled": true,'
        '    "service_desk_enabled": true,'
        '    "service_desk_address": "contact-project+undeadgrishnackh1-gitlabapi-51648656-issue-@incoming.gitlab.com",'
        '    "can_create_merge_request_in": true,'
        '    "issues_access_level": "enabled",'
        '    "repository_access_level": "enabled",'
        '    "merge_requests_access_level": "enabled",'
        '    "forking_access_level": "enabled",'
        '    "wiki_access_level": "enabled",'
        '    "builds_access_level": "enabled",'
        '    "snippets_access_level": "enabled",'
        '    "pages_access_level": "private",'
        '    "analytics_access_level": "enabled",'
        '    "container_registry_access_level": "enabled",'
        '    "security_and_compliance_access_level": "private",'
        '    "releases_access_level": "enabled",'
        '    "environments_access_level": "enabled",'
        '    "feature_flags_access_level": "enabled",'
        '    "infrastructure_access_level": "enabled",'
        '    "monitor_access_level": "enabled",'
        '    "model_experiments_access_level": "enabled",'
        '    "emails_disabled": false,'
        '    "emails_enabled": true,'
        '    "shared_runners_enabled": true,'
        '    "lfs_enabled": true,'
        '    "creator_id": 18503521,'
        '    "import_url": null,'
        '    "import_type": null,'
        '    "import_status": "none",'
        '    "import_error": null,'
        '    "open_issues_count": 0,'
        '    "description_html": "",'
        '    "updated_at": "2023-10-27T16:04:58.262Z",'
        '    "ci_default_git_depth": 20,'
        '    "ci_forward_deployment_enabled": true,'
        '    "ci_forward_deployment_rollback_allowed": true,'
        '    "ci_job_token_scope_enabled": false,'
        '    "ci_separated_caches": true,'
        '    "ci_allow_fork_pipelines_to_run_in_parent_project": true,'
        '    "build_git_strategy": "fetch",'
        '    "keep_latest_artifact": true,'
        '    "restrict_user_defined_variables": false,'
        '    "runners_token": "GR1348941-Nh3G8-8UTCTKDfnh9sz",'
        '    "runner_token_expiration_interval": null,'
        '    "group_runners_enabled": true,'
        '    "auto_cancel_pending_pipelines": "enabled",'
        '    "build_timeout": 3600,'
        '    "auto_devops_enabled": false,'
        '    "auto_devops_deploy_strategy": "continuous",'
        '    "ci_config_path": "",'
        '    "public_jobs": true,'
        '    "shared_with_groups": [],'
        '    "only_allow_merge_if_pipeline_succeeds": false,'
        '    "allow_merge_on_skipped_pipeline": null,'
        '    "request_access_enabled": true,'
        '    "only_allow_merge_if_all_discussions_are_resolved": false,'
        '    "remove_source_branch_after_merge": true,'
        '    "printing_merge_request_link_enabled": true,'
        '    "merge_method": "merge",'
        '    "squash_option": "default_off",'
        '    "enforce_auth_checks_on_uploads": true,'
        '    "suggestion_commit_message": null,'
        '    "merge_commit_template": null,'
        '    "squash_commit_template": null,'
        '    "issue_branch_template": null,'
        '    "autoclose_referenced_issues": true,'
        '    "approvals_before_merge": 0,'
        '    "mirror": false,'
        '    "external_authorization_classification_label": "",'
        '    "marked_for_deletion_at": null,'
        '    "marked_for_deletion_on": null,'
        '    "requirements_enabled": true,'
        '    "requirements_access_level": "enabled",'
        '    "security_and_compliance_enabled": true,'
        '    "compliance_frameworks": [],'
        '    "issues_template": null,'
        '    "merge_requests_template": null,'
        '    "merge_pipelines_enabled": false,'
        '    "merge_trains_enabled": false,'
        '    "merge_trains_skip_train_allowed": false,'
        '    "only_allow_merge_if_all_status_checks_passed": false,'
        '    "allow_pipeline_trigger_approve_deployment": false,'
        '    "permissions": {'
        '        "project_access": null,'
        '        "group_access": {'
        '            "access_level": 50,'
        '            "notification_level": 3'
        "        }"
        "    }"
        "}"
    )
)


stub_gitlab_api_v4_project_12345678_json = json.loads(("{" '   "message": "404 Project Not Found"' "}"))
